api_url = "https://battlemythe.net/api"
# api_url = "http://192.168.1.27:5000/api"

LOBBY = "LOBBY"
REGLES = "REGLES"
CHOOSE_CATEGORY = "CHOOSE_CATEGORY"
LOADING = "LOADING"
MUSIC_PLAY = "MUSIC_PLAY"
END = "END"
SCORES = "SCORES"
